# Generated by Django 2.2.13 on 2020-11-15 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text="Provider's Brand", max_length=100, null=True, verbose_name='Company')),
                ('address', models.CharField(help_text="Company's Address", max_length=250, null=True, verbose_name='Address')),
                ('email', models.EmailField(help_text="Company's Email", max_length=254, null=True, verbose_name='Email')),
                ('contact', models.CharField(help_text='Providers Contact', max_length=100, null=True, verbose_name='Phone Number')),
                ('provider_type', models.CharField(blank=True, choices=[('LP', 'Laboratory'), ('MP', 'Medical Provider')], help_text="Provider's Type", max_length=100, null=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Visitor's First Name", max_length=100, null=True, verbose_name="Visitor's Name")),
                ('last_name', models.CharField(blank=True, help_text="Visitor's First Name", max_length=100, null=True, verbose_name="Visitor's Name")),
                ('contact', models.CharField(help_text='Providers Contact', max_length=100, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text="Company's Email", max_length=254, null=True, verbose_name='Email')),
                ('company', models.ForeignKey(help_text='Providers Brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.Providers')),
            ],
        ),
    ]
