# Generated by Django 2.2.13 on 2020-11-15 21:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0002_providers_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providers',
            unique_together={('company', 'created_by')},
        ),
    ]
