# Generated by Django 2.2.13 on 2020-11-17 03:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0003_auto_20201115_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='contact',
            field=models.CharField(help_text="Visitor's Contact", max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(help_text="Visitor's Email", max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(blank=True, help_text="Visitor's Last Name", max_length=100, null=True, verbose_name="Visitor's Name"),
        ),
    ]
