# Generated by Django 2.2.13 on 2020-12-13 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('providers', '0005_auto_20201122_2255'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Providers',
            new_name='Provider',
        ),
    ]
