# Generated by Django 3.1.6 on 2021-07-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20210108_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(blank=True, help_text="Company's Address", max_length=250, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact',
            field=models.CharField(blank=True, help_text='Providers Contact', max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(blank=True, help_text="Company's Email", max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='contact',
            field=models.CharField(blank=True, help_text="Visitor's Contact", max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(blank=True, help_text="Visitor's Email", max_length=254, null=True, verbose_name='Email'),
        ),
    ]
