# Generated by Django 3.1.6 on 2021-07-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0009_auto_20210717_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='last_name',
            field=models.CharField(help_text="Visitor's Last Name", max_length=100, null=True, verbose_name="Visitor's Last Name"),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(help_text="Visitor's First Name", max_length=100, null=True, verbose_name="Visitor's Name"),
        ),
    ]
