# Generated by Django 2.2.13 on 2020-06-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll',
            field=models.CharField(choices=[('D', 'Doctor'), ('A', 'Assistant')], max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, choices=[('A&I', 'ALLERGY & IMMUNOLOGY'), ('A', 'ANESTHESIOLOGY'), ('DM', 'DERMATOLOGY'), ('DT', 'DENTIST'), ('DR', 'DIAGNOSTIC RADIOLOGY'), ('EM', 'EMERGENCY MEDICINE'), ('FM', 'FAMILY MEDICINE'), ('IM', 'INTERNAL MEDICINE'), ('MG', 'MEDICAL GENETICS'), ('NEU', 'NEUROLOGY'), ('NM', 'NUCLEAR MEDICINE'), ('OG', 'OBSTETRICS AND GYNECOLOGY'), ('OP', 'OPHTHALMOLOGY'), ('PT', 'PATHOLOGY'), ('PD', 'PEDIATRICS'), ('PMR', 'PHYSICAL MEDICINE & REHABILITATION'), ('PM', 'PREVENTIVE MEDICINE'), ('PS', 'PSYCHIATRY'), ('RO', 'RADIATION ONCOLOGY'), ('S', 'SURGERY'), ('U', 'UROLOGY')], help_text='If your roll is (A, Assistant), leave this field blank.', max_length=100),
        ),
    ]
