# Generated by Django 2.2.13 on 2020-06-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usersprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Provide your address', max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='birth_date',
            field=models.DateField(blank=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Femenine'), ('U', 'Undefined')], max_length=25, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('H', 'Honduras')], help_text='Provide your location', max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
