# Generated by Django 2.2.13 on 2020-06-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200623_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Let us know about you', null=True, verbose_name='biography'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Femenine'), ('U', 'Undefined')], max_length=25, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('H', 'Honduras')], help_text='Provide your location', max_length=100, null=True, verbose_name='location'),
        ),
    ]
