# Generated by Django 2.2.13 on 2020-06-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200623_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='address',
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculine'), ('F', 'Femenine'), ('U', 'Undefined')], max_length=25, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.CharField(choices=[('H', 'Honduras')], help_text='Provide your location', max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
