# Generated by Django 2.2.13 on 2020-06-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200623_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.CharField(choices=[('HN', 'Honduras')], help_text='Provide your location', max_length=100, null=True, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='accounts/profile_pictures', verbose_name='profile picture'),
        ),
    ]
