# Generated by Django 2.2.13 on 2020-06-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200624_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Provide your phone number', max_length=15, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(help_text='Let us see you! Upload a profile picture', null=True, upload_to='accounts/profile_pictures', verbose_name='profile picture'),
        ),
    ]
