# Generated by Django 2.2.13 on 2020-06-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200624_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Let us see you! Upload a profile picture', null=True, upload_to='accounts/profile_pictures', verbose_name='profile picture'),
        ),
    ]
