# Generated by Django 2.2.13 on 2020-06-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200624_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='address',
            field=models.CharField(help_text='Provide your exact address', max_length=200, null=True, verbose_name='address'),
        ),
    ]
