# Generated by Django 2.2.13 on 2020-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usersprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='address',
            field=models.TextField(help_text='Provide your exact address', max_length=200, null=True, verbose_name='address'),
        ),
    ]
