# Generated by Django 2.2.13 on 2020-06-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200627_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='origin',
            field=models.CharField(choices=[('Honduras', 'Honduras')], max_length=50, null=True, verbose_name='origin'),
        ),
    ]
