# Generated by Django 2.2.13 on 2020-07-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_usersprofile_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='origin',
            field=models.CharField(choices=[('HND', 'Honduras')], max_length=50, null=True, verbose_name='origin'),
        ),
    ]
