# Generated by Django 2.2.13 on 2020-07-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20200707_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='tzone',
            field=models.CharField(help_text='Provide your timezone', max_length=40, null=True, verbose_name='timezone'),
        ),
    ]
