# Generated by Django 2.2.13 on 2020-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20201101_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='background_pic',
            field=models.ImageField(blank=True, help_text='Let us see you! Upload a profile picture', null=True, upload_to='accounts/background_pictures', verbose_name='profile picture'),
        ),
    ]
