# Generated by Django 2.2.13 on 2021-01-03 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_usersprofile_background_pic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'ordering': ['user'], 'verbose_name': 'user_profile', 'verbose_name_plural': 'user_profiles'},
        ),
        migrations.CreateModel(
            name='MailingCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(blank=True, help_text='Provide the SMTP Server', max_length=100, null=True, verbose_name='SMTP Server')),
                ('email_port', models.IntegerField(blank=True, help_text='Provide the port used by your server', null=True, verbose_name='Port')),
                ('email_host_user', models.EmailField(blank=True, help_text='Provide your email', max_length=254, null=True, verbose_name='Email')),
                ('email_host_password', models.CharField(blank=True, help_text='Provide your password', max_length=254, null=True, verbose_name='Password')),
                ('email_use_tls', models.BooleanField(default=False, verbose_name='TLS')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
