# Generated by Django 2.2.13 on 2021-01-03 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20210103_0155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingcredential',
            old_name='email_host_user',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='mailingcredential',
            old_name='email_host_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='mailingcredential',
            old_name='email_port',
            new_name='port',
        ),
        migrations.RenameField(
            model_name='mailingcredential',
            old_name='email_host',
            new_name='smtp_server',
        ),
        migrations.RenameField(
            model_name='mailingcredential',
            old_name='email_use_tls',
            new_name='use_tls',
        ),
    ]
