# Generated by Django 2.2.13 on 2021-01-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210103_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcredential',
            name='smtp_server',
            field=models.CharField(blank=True, default='', help_text='Provide the SMTP Server', max_length=100, null=True, verbose_name='SMTP Server'),
        ),
        migrations.AlterField(
            model_name='mailingcredential',
            name='use_tls',
            field=models.BooleanField(default=False, verbose_name='Use TLS? (Recommended)'),
        ),
    ]
