# Generated by Django 2.2.13 on 2021-01-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20210104_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingcredential',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailing_credentials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/background_pictures', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_pictures', verbose_name='profile picture'),
        ),
    ]
