# Generated by Django 2.2.13 on 2021-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210106_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingcredential',
            options={'verbose_name': 'Mailing Credential', 'verbose_name_plural': 'Mailing Credentials'},
        ),
        migrations.AlterModelOptions(
            name='usersprofile',
            options={'ordering': ['user'], 'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='address',
            field=models.TextField(help_text='Provide your exact address', max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='background_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/background_pictures', verbose_name='Background Picture'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Let us know about you', null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(choices=[('Masculine', 'Masculine'), ('Femenine', 'Femenine'), ('Undefined', 'Undefined')], max_length=25, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='location',
            field=models.CharField(choices=[('HND', 'Honduras')], help_text='Provide your location', max_length=100, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='origin',
            field=models.CharField(choices=[('HND', 'Honduras')], max_length=50, null=True, verbose_name='Origin'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Provide your phone number', max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_pictures', verbose_name='Profile Picture'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='tzone',
            field=models.CharField(help_text='Provide your timezone', max_length=40, null=True, verbose_name='Timezone'),
        ),
    ]
