# Generated by Django 2.2.13 on 2021-01-11 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20210108_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='contacts',
            field=models.ManyToManyField(blank=True, help_text='Contacts List', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='speciality',
            field=models.CharField(blank=True, choices=[('ALLERGY & IMMUNOLOGY', 'Allergy & Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DENTIST', 'Dentist'), ('DIAGNOSTIC RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY MEDICINE', 'Emergency Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('MEDICAL GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics & Gynechology'), ('OPHTHALMOLOGY', 'Ophthalmolgy'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL MEDICINE & REHABILITATION', 'Physical Medicine & Rehabilitation'), ('PREVENTIVE MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology')], help_text='If your roll is (A, Assistant), leave this field blank.', max_length=100, verbose_name='Speciality'),
        ),
    ]
