# Generated by Django 2.2.13 on 2021-02-01 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20210127_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.ImageField(help_text="User's Wallpaper", upload_to='', verbose_name='Wallpaper')),
                ('user', models.OneToOneField(blank=True, help_text='User Settings', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User Settings')),
            ],
        ),
    ]
