# Generated by Django 2.2.13 on 2021-02-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_usersetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name': 'User Setting', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='wallpaper',
            field=models.ImageField(blank=True, help_text="User's Wallpaper", null=True, upload_to='', verbose_name='Wallpaper'),
        ),
    ]
