# Generated by Django 2.2.13 on 2021-02-03 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20210201_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User Settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='User Settings'),
        ),
    ]
