# Generated by Django 2.2.13 on 2021-02-03 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20210203_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='wallpaper',
            field=models.CharField(blank=True, help_text='Choose Wallpaper', max_length=2, null=True, verbose_name='Wallpaper'),
        ),
    ]
