# Generated by Django 2.2.13 on 2021-02-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20210203_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='wallpaper',
            field=models.IntegerField(blank=True, help_text='Choose Wallpaper', null=True, verbose_name='Wallpaper'),
        ),
    ]
