# Generated by Django 2.2.13 on 2021-02-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20210203_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='availability',
            field=models.CharField(choices=[('Available', 'A'), ('Busy', 'B')], help_text='User Availability', max_length=50, null=True, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='usersetting',
            name='wallpaper',
            field=models.CharField(blank=True, help_text='Choose Wallpaper', max_length=100, null=True, verbose_name='Wallpaper'),
        ),
    ]
