# Generated by Django 2.2.13 on 2021-02-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_auto_20210207_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='availability',
            field=models.CharField(blank=True, choices=[('A', 'Available'), ('B', 'Busy')], help_text='User Availability', max_length=50, null=True, verbose_name='Availability'),
        ),
    ]
