# Generated by Django 2.2.13 on 2021-02-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20210207_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='background_pic',
        ),
    ]
