# Generated by Django 3.1.6 on 2021-04-21 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_remove_usersprofile_background_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersetting',
            name='session_expire_time',
            field=models.IntegerField(blank=True, choices=[(300, '5 Minutes'), (600, '10 Minutes'), (1200, '20 Minutes'), (1800, '30 Minutes'), (3600, '1 Hour')], help_text='Provide your session time expire timeout', null=True, verbose_name='Session Expire Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
