# Generated by Django 3.1.6 on 2021-04-21 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20210421_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='session_expire_time',
            field=models.IntegerField(blank=True, choices=[(300, '5 Minutes'), (600, '10 Minutes'), (1200, '20 Minutes'), (1800, '30 Minutes'), (3600, '1 Hour')], default=1800, help_text='Provide your session time expire timeout', null=True, verbose_name='Session Expire Time'),
        ),
    ]
