# Generated by Django 3.1.6 on 2021-04-22 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20210421_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_expire_time', models.IntegerField(blank=True, choices=[(300, '5 Minutes'), (600, '10 Minutes'), (1200, '20 Minutes'), (1800, '30 Minutes'), (3600, '1 Hour')], default=1800, help_text='Provide your session time expire timeout', null=True, verbose_name='Session Expire Time')),
                ('user', models.OneToOneField(blank=True, help_text='User Settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_settings', to=settings.AUTH_USER_MODEL, verbose_name='User Settings')),
            ],
            options={
                'verbose_name': 'User Account Setting',
                'verbose_name_plural': 'User Account Settings',
            },
        ),
        migrations.CreateModel(
            name='UserGeneralSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallpaper', models.CharField(blank=True, help_text='Choose Wallpaper', max_length=100, null=True, verbose_name='Wallpaper')),
                ('user', models.OneToOneField(blank=True, help_text='User Settings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_settings', to=settings.AUTH_USER_MODEL, verbose_name='User Settings')),
            ],
            options={
                'verbose_name': 'User Setting',
                'verbose_name_plural': 'User Settings',
            },
        ),
        migrations.DeleteModel(
            name='UserSetting',
        ),
    ]
