# Generated by Django 3.1.6 on 2021-04-22 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20210422_1735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usergeneralsettings',
            options={'verbose_name': 'User General Setting', 'verbose_name_plural': 'User General Settings'},
        ),
    ]
