# Generated by Django 3.1.6 on 2021-04-26 17:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20210422_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='speciality',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customuser')),
                ('speciality', models.CharField(blank=True, choices=[('ALLERGY & IMMUNOLOGY', 'Allergy & Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DENTIST', 'Dentist'), ('DIAGNOSTIC RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY MEDICINE', 'Emergency Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('MEDICAL GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics & Gynechology'), ('OPHTHALMOLOGY', 'Ophthalmolgy'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL MEDICINE & REHABILITATION', 'Physical Medicine & Rehabilitation'), ('PREVENTIVE MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology')], help_text='If your roll is (A, Assistant), leave this field blank.', max_length=100, verbose_name='Speciality')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.customuser')),
                ('doctors', models.ManyToManyField(blank=True, help_text="Doctor's who this assistant will be working with", to='accounts.Doctor', verbose_name='Doctors')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('accounts.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
