# Generated by Django 3.1.6 on 2021-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20210426_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistant',
            options={'ordering': ['first_name'], 'verbose_name': 'Assistant', 'verbose_name_plural': 'Assistants'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['first_name'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.RemoveField(
            model_name='usersprofile',
            name='tzone',
        ),
        migrations.AddField(
            model_name='useraccountsettings',
            name='tzone',
            field=models.CharField(help_text='Provide your timezone', max_length=40, null=True, verbose_name='Timezone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, choices=[('ALLERGY & IMMUNOLOGY', 'Allergy & Immunology'), ('ANESTHESIOLOGY', 'Anesthesiology'), ('DERMATOLOGY', 'Dermatology'), ('DENTIST', 'Dentist'), ('DIAGNOSTIC RADIOLOGY', 'Diagnostic Radiology'), ('EMERGENCY MEDICINE', 'Emergency Medicine'), ('FAMILY MEDICINE', 'Family Medicine'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('MEDICAL GENETICS', 'Medical Genetics'), ('NEUROLOGY', 'Neurology'), ('NUCLEAR MEDICINE', 'Nuclear Medicine'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics & Gynechology'), ('OPHTHALMOLOGY', 'Ophthalmolgy'), ('PATHOLOGY', 'Pathology'), ('PEDIATRICS', 'Pediatrics'), ('PHYSICAL MEDICINE & REHABILITATION', 'Physical Medicine & Rehabilitation'), ('PREVENTIVE MEDICINE', 'Preventive Medicine'), ('PSYCHIATRY', 'Psychiatry'), ('RADIATION ONCOLOGY', 'Radiation Oncology'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology')], help_text="Doctor's Speciality", max_length=100, verbose_name='Speciality'),
        ),
    ]
