# Generated by Django 3.1.6 on 2021-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20210426_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountsettings',
            name='tzone',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='tzone',
            field=models.CharField(help_text='Provide your timezone', max_length=40, null=True, verbose_name='Timezone'),
        ),
    ]
