# Generated by Django 3.1.6 on 2021-04-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_auto_20210427_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='linking_id',
            field=models.CharField(blank=True, help_text='Used by Assistants to link to Doctors', max_length=14, null=True, unique=True, verbose_name='Linking ID'),
        ),
    ]
