# Generated by Django 3.1.6 on 2021-05-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20210427_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, choices=[('ALLERGY & IMMUNOLOGY', 'Allergy & Immunology'), ('DENTIST', 'Dentist'), ('INTERNAL MEDICINE', 'Internal Medicine'), ('GENERAL MEDICINE', 'General Medicine'), ('NEUROLOGY', 'Neurology'), ('OBSTETRICS AND GYNECOLOGY', 'Obstetrics & Gynecology'), ('OPHTHALMOLOGY', 'Ophthalmology'), ('PEDIATRICS', 'Pediatrics'), ('PSYCHIATRY', 'Psychiatry'), ('SURGERY', 'Surgery'), ('UROLOGY', 'Urology')], help_text="Doctor's Speciality", max_length=100, verbose_name='Speciality'),
        ),
    ]
