# Generated by Django 3.1.6 on 2021-05-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_auto_20210507_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roll',
            field=models.CharField(choices=[('DOCTOR', 'Doctor'), ('ASSISTANT', 'Assistant')], help_text='Choose the roll you will acquire in this account.', max_length=25, verbose_name='Roll'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='speciality',
            field=models.CharField(blank=True, choices=[('A&I', 'Allergy & Immunology'), ('DT', 'Dentist'), ('IM', 'Internal Medicine'), ('GM', 'General Medicine'), ('NEU', 'Neurology'), ('O&G', 'Obstetrics & Gynecology'), ('OPH', 'Ophthalmology'), ('PED', 'Pediatrics'), ('PSY', 'Psychiatry'), ('SRG', 'Surgery'), ('URO', 'Urology')], help_text="Doctor's Speciality", max_length=100, verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='phone_number',
            field=models.CharField(help_text='Provide your phone number', max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
