# Generated by Django 3.1.6 on 2021-05-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210510_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.TextField(blank=True, help_text="Chat's last message", null=True, verbose_name="Chat's last message"),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message_sender',
            field=models.ForeignKey(blank=True, help_text='Last message sender', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Last message sender'),
        ),
        migrations.AlterField(
            model_name='usersprofile',
            name='gender',
            field=models.CharField(choices=[('MASCULINE', 'Masculine'), ('FEMENINE', 'Femenine')], max_length=25, null=True, verbose_name='Gender'),
        ),
    ]
