# Generated by Django 3.1.6 on 2021-07-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20210521_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountsettings',
            name='sfx',
            field=models.BooleanField(blank=True, default=True, help_text='Sound Effects Switch', null=True, verbose_name='SFX'),
        ),
    ]
