# Generated by Django 3.1.6 on 2021-07-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_useraccountsettings_sfx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccountsettings',
            name='sfx',
        ),
        migrations.AddField(
            model_name='usergeneralsettings',
            name='sfx',
            field=models.BooleanField(blank=True, default=True, help_text='Sound Effects Switch', null=True, verbose_name='SFX'),
        ),
    ]
