# Generated by Django 3.1.6 on 2021-07-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_auto_20210703_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='subscription',
            field=models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium')], default='BASIC', help_text='Account Subscription Type', max_length=10, null=True, verbose_name='Subscription'),
        ),
    ]
