# Generated by Django 3.1.6 on 2021-07-09 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_doctor_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, help_text='Message time creation', null=True, verbose_name='datetime')),
                ('text', models.TextField(blank=True, help_text='Message Text', null=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, help_text='Message Image', null=True, upload_to='', verbose_name='Image')),
                ('chat', models.ForeignKey(blank=True, help_text='Chat', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.chat', verbose_name='Sender')),
                ('created_by', models.ForeignKey(blank=True, help_text='Sender', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
        ),
    ]
