# Generated by Django 3.1.6 on 2021-07-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(blank=True, help_text='Chat', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='accounts.chat', verbose_name='Chat'),
        ),
    ]
