# Generated by Django 3.1.6 on 2021-07-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_message_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('UNREAD', 'Unread'), ('READ', 'Read')], default='UNREAD', help_text='Message Status', max_length=6, null=True, verbose_name='status'),
        ),
    ]
