# Generated by Django 3.1.6 on 2021-07-13 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_auto_20210710_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersprofile',
            name='block_list',
            field=models.ForeignKey(blank=True, help_text="User's Block List", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to=settings.AUTH_USER_MODEL, verbose_name='Block List'),
        ),
    ]
