# Generated by Django 3.1.6 on 2021-07-13 23:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_usersprofile_block_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='block_list',
        ),
        migrations.AddField(
            model_name='usersprofile',
            name='block_list',
            field=models.ManyToManyField(blank=True, help_text="User's Block List", related_name='block_list', to=settings.AUTH_USER_MODEL, verbose_name='Block List'),
        ),
    ]
