# Generated by Django 3.1.6 on 2021-07-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_auto_20210713_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergeneralsettings',
            name='notifications',
            field=models.BooleanField(blank=True, default=True, help_text='Notifications', null=True, verbose_name='Notifications'),
        ),
    ]
