# Generated by Django 3.1.6 on 2021-07-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_usergeneralsettings_notifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Provide your exact address', max_length=200, null=True, verbose_name='Address'),
        ),
    ]
