# Generated by Django 3.1.6 on 2021-07-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_auto_20210720_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Provide your phone number', max_length=15, null=True, verbose_name='Phone Number'),
        ),
    ]
