# Generated by Django 3.1.6 on 2021-07-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_auto_20210720_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersprofile',
            name='birth_date',
            field=models.DateField(help_text='Birth date', null=True, verbose_name='Birth Date'),
        ),
    ]
