# Generated by Django 3.1.6 on 2021-07-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_auto_20210720_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, help_text='Product ID', max_length=255, null=True, verbose_name='Product ID')),
                ('user_type', models.CharField(choices=[('DOCTOR', 'Doctor'), ('ASSISTANT', 'Assistant')], help_text='Product User Type', max_length=50, null=True, verbose_name='Product User Type')),
                ('plan', models.CharField(choices=[('PREMIUM', 'Premium')], help_text='Product Plan Type', max_length=50, null=True, verbose_name='Product Plan Type')),
                ('name_id', models.CharField(blank=True, help_text='Product Name ID', max_length=50, null=True, verbose_name='Name ID')),
                ('name', models.CharField(blank=True, help_text='Product Name', max_length=50, null=True, verbose_name='Name')),
                ('description', models.TextField(help_text='Product Description', null=True, verbose_name='Description')),
                ('product_type', models.CharField(choices=[('SERVICE', 'Service')], default='Service', help_text='Product Type', max_length=50, null=True, verbose_name='Type')),
                ('category', models.CharField(choices=[('SOFTWARE', 'Software')], default='Software', help_text='Product Category', max_length=50, null=True, verbose_name='Category')),
                ('image', models.ImageField(blank=True, help_text='Product Image', null=True, upload_to='', verbose_name='Image')),
                ('home_image', models.ImageField(blank=True, help_text='Product Image', null=True, upload_to='', verbose_name='Home Image')),
                ('get_product_url', models.URLField(blank=True, help_text='Get Product URL', null=True, verbose_name='Get Product URL')),
                ('edit_product_url', models.URLField(blank=True, help_text='Edit Product URL', null=True, verbose_name='Edit Product URL')),
            ],
        ),
    ]
