# Generated by Django 3.1.6 on 2021-07-28 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_plan_id', models.CharField(blank=True, help_text='Product Plan ID', max_length=255, null=True, verbose_name='Product ID')),
                ('user_type', models.CharField(help_text='Product User Type', max_length=50, null=True, verbose_name='Product User Type')),
                ('plan', models.CharField(help_text='Product Plan Type', max_length=50, null=True, verbose_name='Product Plan Type')),
                ('name_id', models.CharField(blank=True, help_text='Plan Name ID', max_length=50, null=True, verbose_name='Name ID')),
                ('name', models.CharField(blank=True, help_text='Plan Name', max_length=50, null=True, verbose_name='Name')),
                ('description', models.TextField(help_text='Plan Description', null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], help_text='Plan Status', max_length=50, null=True, verbose_name='Status')),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly')], help_text='Plan Billing Frequency', max_length=50, null=True, verbose_name='Frequency')),
                ('price', models.CharField(help_text='Plan Price', max_length=5, null=True, verbose_name='Price')),
                ('tenure', models.CharField(choices=[('TRIAL', 'Trial'), ('REGULAR', 'Regular')], help_text='Plan Tenure', max_length=50, null=True, verbose_name='Tenure')),
                ('sequence', models.CharField(help_text='Plan Sequence', max_length=2, null=True, verbose_name='Sequence')),
                ('total_cycles', models.IntegerField(help_text='Cycles to be billed', null=True, verbose_name='Cycles')),
                ('auto_billing', models.BooleanField(help_text='Plan Billing Type', null=True, verbose_name='Auto Billing')),
                ('setup_fee', models.IntegerField(default=0, help_text='Setup Fee', null=True, verbose_name='Setup Fee')),
                ('setup_fee_failure_action', models.CharField(choices=[('CANCEL', 'Cancel'), ('CONTINUE', 'Continue')], help_text='Billing Failure Action', max_length=10, null=True, verbose_name='Billing Failure Action')),
                ('payment_failure_threshold', models.IntegerField(help_text='Payment Failure Threshold', null=True, verbose_name='Payment Failure Threshold')),
                ('get_plan_url', models.URLField(blank=True, help_text='Get Plan URL', null=True, verbose_name='Get Plan URL')),
                ('edit_plan_url', models.URLField(blank=True, help_text='Edit Plan URL', null=True, verbose_name='Edit Plan URL')),
                ('deactivate_plan_url', models.URLField(blank=True, help_text='Deactivate Plan URL', null=True, verbose_name='Deactivate Plan URL')),
                ('product', models.ForeignKey(help_text='Plan Product', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_plan', to='accounts.product', verbose_name='Plan Product')),
            ],
        ),
    ]
