# Generated by Django 3.1.6 on 2021-07-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(blank=True, help_text='Product Plan Type', max_length=50, null=True, verbose_name='Product Plan Type'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user_type',
            field=models.CharField(blank=True, help_text='Product User Type', max_length=50, null=True, verbose_name='Product User Type'),
        ),
    ]
