# Generated by Django 3.1.6 on 2021-07-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0073_auto_20210728_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='frequency',
            field=models.CharField(choices=[('MONTH', 'Monthly')], help_text='Plan Billing Frequency', max_length=50, null=True, verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(blank=True, help_text='Plan Name', max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name_id',
            field=models.CharField(blank=True, help_text='Plan Name ID', max_length=50, null=True, unique=True, verbose_name='Name ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, help_text='Product Name', max_length=50, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_id',
            field=models.CharField(blank=True, help_text='Product Name ID', max_length=50, null=True, unique=True, verbose_name='Name ID'),
        ),
    ]
