# Generated by Django 3.1.6 on 2021-07-28 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_auto_20210728_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(help_text='Subscription ID', max_length=255, null=True, verbose_name='Subscription ID')),
                ('user', models.ForeignKey(help_text='Subscription User', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to=settings.AUTH_USER_MODEL, verbose_name='Subscription User')),
            ],
        ),
    ]
