# Generated by Django 3.1.6 on 2021-07-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0075_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmed',
            field=models.BooleanField(default=False, help_text='Confirmed User Account', null=True, verbose_name='Confirmed?'),
        ),
    ]
