# Generated by Django 2.2.13 on 2020-07-10 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0024_patient_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date the consult will be done', null=True, verbose_name='Date of the consult')),
                ('time', models.TimeField(help_text='Time the consult will be done', null=True, verbose_name='Time of the consult')),
                ('motive', models.CharField(default='Protocol', help_text='The motive of your assistance to the consult', max_length=100, null=True, verbose_name='motive of the consult')),
                ('suffering', models.CharField(help_text='What is the patient suffering?', max_length=250, null=True, verbose_name='suffering')),
                ('created_by', models.ForeignKey(help_text='Creator of the consult', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('patient', models.ForeignKey(help_text='Patient assisting, this consult', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patient', verbose_name='patient')),
            ],
            options={
                'unique_together': {('patient', 'date', 'time')},
            },
        ),
    ]
