# Generated by Django 2.2.13 on 2020-07-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cie10Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='CIE-10 Code', max_length=50, null=True, verbose_name='code')),
            ],
        ),
        migrations.AddField(
            model_name='consults',
            name='actions',
            field=models.TextField(blank=True, help_text='actions', null=True, verbose_name='actions'),
        ),
        migrations.AddField(
            model_name='consults',
            name='analysis',
            field=models.TextField(blank=True, help_text='Analysis', null=True, verbose_name='analysis'),
        ),
        migrations.AddField(
            model_name='consults',
            name='blood_pressure',
            field=models.FloatField(blank=True, help_text='blood pressure', null=True, verbose_name='blood pressure'),
        ),
        migrations.AddField(
            model_name='consults',
            name='cie_10_detail',
            field=models.TextField(blank=True, help_text='CIE-10 diagnose details', null=True, verbose_name='CIE-10 Detail'),
        ),
        migrations.AddField(
            model_name='consults',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='consults',
            name='diagnose',
            field=models.TextField(blank=True, help_text='Diagnose', null=True, verbose_name='diagnose'),
        ),
        migrations.AddField(
            model_name='consults',
            name='digestive_system',
            field=models.TextField(blank=True, help_text='digestive system analysis', null=True, verbose_name='digestive system'),
        ),
        migrations.AddField(
            model_name='consults',
            name='doses',
            field=models.TextField(blank=True, help_text='doses', null=True, verbose_name='doses'),
        ),
        migrations.AddField(
            model_name='consults',
            name='endocrine_system',
            field=models.TextField(blank=True, help_text='endocrine system analysis', null=True, verbose_name='endocrine system'),
        ),
        migrations.AddField(
            model_name='consults',
            name='head_exploration',
            field=models.TextField(blank=True, help_text='head exploration analysis', null=True, verbose_name='head exploration'),
        ),
        migrations.AddField(
            model_name='consults',
            name='lymphatic_system',
            field=models.TextField(blank=True, help_text='lymphatic system analysis', null=True, verbose_name='lymphatic system'),
        ),
        migrations.AddField(
            model_name='consults',
            name='medical_exams',
            field=models.FileField(blank=True, help_text='Attach exams if availalble', null=True, upload_to='appointmens/exams', verbose_name='medical exams'),
        ),
        migrations.AddField(
            model_name='consults',
            name='medicine',
            field=models.TextField(blank=True, help_text='Medicine', null=True, verbose_name='medicine'),
        ),
        migrations.AddField(
            model_name='consults',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='consults',
            name='procedure',
            field=models.TextField(blank=True, help_text='Procedure', null=True, verbose_name='procedure'),
        ),
        migrations.AddField(
            model_name='consults',
            name='renal_system',
            field=models.TextField(blank=True, help_text='renal system analysis', null=True, verbose_name='renal system'),
        ),
        migrations.AddField(
            model_name='consults',
            name='respiratory_system',
            field=models.TextField(blank=True, help_text='respiratory system analysis', null=True, verbose_name='respiratory system'),
        ),
        migrations.AddField(
            model_name='consults',
            name='size',
            field=models.FloatField(blank=True, help_text='size', null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='consults',
            name='temperature',
            field=models.FloatField(blank=True, help_text='body temperature', null=True, verbose_name='temperature'),
        ),
        migrations.AddField(
            model_name='consults',
            name='thorax_exploration',
            field=models.TextField(blank=True, help_text='thorax exploration analysis', null=True, verbose_name='thorax exploration'),
        ),
        migrations.AddField(
            model_name='consults',
            name='use',
            field=models.TextField(blank=True, help_text='use', null=True, verbose_name='use'),
        ),
        migrations.AddField(
            model_name='consults',
            name='weight',
            field=models.FloatField(blank=True, help_text='weight', null=True, verbose_name='weight'),
        ),
        migrations.AddField(
            model_name='consults',
            name='cie_10_group',
            field=models.OneToOneField(blank=True, help_text='CIE-10 group for the diagnose', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciegroup', to='appointments.Cie10Group', verbose_name='CIE-10 Group'),
        ),
    ]
