# Generated by Django 2.2.13 on 2020-07-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_patient_created_by'),
        ('appointments', '0004_auto_20200710_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='datetime',
            field=models.DateTimeField(help_text='Date the consult will be done', null=True, verbose_name='Date of the consult'),
        ),
        migrations.AlterUniqueTogether(
            name='consults',
            unique_together={('patient', 'datetime')},
        ),
        migrations.RemoveField(
            model_name='consults',
            name='date',
        ),
        migrations.RemoveField(
            model_name='consults',
            name='time',
        ),
    ]
