# Generated by Django 2.2.13 on 2020-07-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_auto_20200710_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='motive',
            field=models.TextField(help_text='The motive of your assistance to the consult', null=True, verbose_name='motive of the consult'),
        ),
        migrations.AlterField(
            model_name='consults',
            name='suffering',
            field=models.TextField(help_text='What is the patient suffering?', null=True, verbose_name='suffering'),
        ),
    ]
