# Generated by Django 2.2.13 on 2020-07-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20200710_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='status',
            field=models.IntegerField(blank=True, default=-1, help_text='Handles the consult status', null=True, verbose_name='status'),
        ),
    ]
