# Generated by Django 2.2.13 on 2020-07-14 03:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_consults_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='created_at',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='moment created', null=True, verbose_name='created at'),
        ),
    ]
