# Generated by Django 2.2.13 on 2020-07-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_consults_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consults',
            name='description',
        ),
        migrations.RemoveField(
            model_name='consults',
            name='doses',
        ),
        migrations.RemoveField(
            model_name='consults',
            name='use',
        ),
    ]
