# Generated by Django 2.2.13 on 2020-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20200716_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='status',
            field=models.BooleanField(blank=True, default=False, help_text='Handles the consult status', null=True, verbose_name='status'),
        ),
    ]
