# Generated by Django 2.2.13 on 2020-07-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20200718_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consults',
            name='created_at',
        ),
        migrations.AddField(
            model_name='consults',
            name='medical_status',
            field=models.BooleanField(blank=True, default=False, help_text='Handles the medical consult status', null=True, verbose_name='medical_status'),
        ),
        migrations.AlterField(
            model_name='consults',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', help_text='Handles the consult status', max_length=10, null=True, verbose_name='status'),
        ),
    ]
