# Generated by Django 2.2.13 on 2020-07-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20200722_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='drugs name', max_length=200, null=True, unique=True, verbose_name='drugs')),
            ],
        ),
    ]
