# Generated by Django 2.2.13 on 2020-07-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Drugs recommended', null=True, related_name='drugs', to='appointments.Drugs', verbose_name='Drugs'),
        ),
    ]
