# Generated by Django 2.2.13 on 2020-07-28 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20200728_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(blank=True, help_text='drugs name', max_length=200, null=True, verbose_name='drugs'),
        ),
    ]
