# Generated by Django 2.2.13 on 2020-07-29 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0016_auto_20200728_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugs',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Drug created by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
