# Generated by Django 2.2.13 on 2020-09-09 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_drugs_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='patient',
            field=models.ForeignKey(help_text='Patient assisting this consult', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(help_text='drugs name', max_length=200, null=True, verbose_name='drugs'),
        ),
    ]
