# Generated by Django 2.2.13 on 2020-09-11 18:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0018_auto_20200909_1801'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='drugs',
            unique_together={('name', 'created_by')},
        ),
    ]
