# Generated by Django 2.2.13 on 2020-09-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0020_drugs_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='charge',
            field=models.FloatField(default=0.0, help_text='Charge Amount', null=True, verbose_name='charge'),
        ),
        migrations.AlterField(
            model_name='consults',
            name='medical_exams',
            field=models.FileField(blank=True, help_text='Attach exams if available', null=True, upload_to='appointments/exams', verbose_name='medical exams'),
        ),
    ]
