# Generated by Django 2.2.13 on 2020-09-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_auto_20200922_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='charge',
            field=models.FloatField(default=0.0, help_text='Charge Amount', null=True, verbose_name='charge'),
        ),
    ]
