# Generated by Django 2.2.13 on 2020-09-22 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0023_auto_20200922_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='charge',
            field=models.DecimalField(decimal_places=2, help_text='Charge Amount', max_digits=10, null=True, verbose_name='charge'),
        ),
    ]
