# Generated by Django 2.2.13 on 2020-09-26 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0024_auto_20200922_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consults',
            name='medical_exams',
        ),
        migrations.CreateModel(
            name='MedicalExams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='Date the exams were presented', null=True, verbose_name='date')),
                ('type', models.CharField(help_text='Type of exams', max_length=100, null=True, verbose_name='type of exams')),
                ('image', models.ImageField(blank=True, help_text='Exam IMG', null=True, upload_to='', verbose_name='exam')),
                ('consult', models.ForeignKey(blank=True, help_text='Medical Exams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='appointments.Consults', verbose_name='Medical Exams')),
            ],
        ),
    ]
