# Generated by Django 2.2.13 on 2020-09-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_auto_20200926_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexams',
            name='type',
            field=models.CharField(choices=[('T', 'Test')], help_text='Type of exams', max_length=100, null=True, verbose_name='type of exams'),
        ),
    ]
