# Generated by Django 2.2.13 on 2020-10-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_auto_20200926_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='name',
            field=models.CharField(help_text='drugs name', max_length=200, null=True, verbose_name='drug'),
        ),
    ]
