# Generated by Django 2.2.13 on 2020-10-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0028_auto_20201005_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugs',
            name='category',
            field=models.CharField(choices=[('AP', 'Antipyretics'), ('AG', 'Analgesics'), ('AM', 'Antimalarial'), ('AB', 'Antibiotics'), ('AS', 'Antiseptics'), ('MS', 'Mood Stabilizers'), ('HR', 'Hormone Replacement'), ('OC', 'Oral Contraceptives'), ('S', 'Stimulants'), ('T', 'Tranquilizers'), ('ST', 'Statins')], help_text='Category', max_length=50, null=True, verbose_name='category'),
        ),
    ]
