# Generated by Django 2.2.13 on 2020-10-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0029_auto_20201005_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalexams',
            name='date',
        ),
    ]
