# Generated by Django 2.2.13 on 2020-10-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0030_remove_medicalexams_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexams',
            name='date',
            field=models.DateField(blank=True, help_text='Date the exams were presented', null=True, verbose_name='date'),
        ),
    ]
