# Generated by Django 2.2.13 on 2020-11-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0032_auto_20201104_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalexams',
            name='image',
            field=models.ImageField(blank=True, help_text='Exam IMG', null=True, upload_to='appointments/exams', verbose_name='exam'),
        ),
    ]
