# Generated by Django 2.2.13 on 2020-11-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0033_auto_20201109_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='lock',
            field=models.BooleanField(default=True, help_text='Consult lock status', null=True, verbose_name='lock'),
        ),
    ]
