# Generated by Django 2.2.13 on 2020-11-23 15:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0036_auto_20201123_1530'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consults',
            unique_together={('created_by', 'datetime', 'medical_status')},
        ),
    ]
