# Generated by Django 2.2.13 on 2020-11-23 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0040_auto_20201123_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='attended_at',
            field=models.DateTimeField(blank=True, help_text='Time the consult was attended', null=True, verbose_name='attended_at'),
        ),
        migrations.AddField(
            model_name='consults',
            name='finished_at',
            field=models.DateTimeField(blank=True, help_text='Time the consult was finished', null=True, verbose_name='finished_at'),
        ),
        migrations.AlterUniqueTogether(
            name='consults',
            unique_together={('created_by', 'datetime', 'medical_status')},
        ),
    ]
