# Generated by Django 2.2.13 on 2020-11-23 17:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0041_auto_20201123_1738'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consults',
            unique_together={('created_by', 'datetime', 'medical_status', 'attended_at', 'finished_at')},
        ),
    ]
