# Generated by Django 2.2.13 on 2020-11-23 18:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0043_auto_20201123_1746'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consults',
            unique_together={('created_by', 'datetime')},
        ),
        migrations.RemoveField(
            model_name='consults',
            name='attended_at',
        ),
        migrations.RemoveField(
            model_name='consults',
            name='finished_at',
        ),
    ]
