# Generated by Django 2.2.13 on 2020-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0044_auto_20201123_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='consults',
            name='prescription',
            field=models.FileField(blank=True, help_text="Current consult's prescription", null=True, upload_to='appointments/prescriptions', verbose_name='prescription'),
        ),
    ]
