# Generated by Django 2.2.13 on 2020-11-30 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0045_consults_prescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consults',
            old_name='medicine',
            new_name='indications',
        ),
    ]
