# Generated by Django 2.2.13 on 2020-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0046_auto_20201130_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consults',
            name='indications',
            field=models.TextField(blank=True, help_text='Indications', null=True, verbose_name='indications'),
        ),
    ]
