# Generated by Django 2.2.13 on 2020-12-13 16:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('patients', '0042_auto_20201213_1534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0047_auto_20201213_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Consults',
            new_name='Consult',
        ),
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
        migrations.RenameModel(
            old_name='MedicalExams',
            new_name='MedicalExam',
        ),
    ]
