# Generated by Django 2.2.13 on 2021-01-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0048_auto_20201213_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consult',
            name='actions',
            field=models.TextField(blank=True, help_text='Actions', null=True, verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='analysis',
            field=models.TextField(blank=True, help_text='Analysis', null=True, verbose_name='Analysis'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='blood_pressure',
            field=models.FloatField(blank=True, help_text='Blood Pressure', null=True, verbose_name='Blood Pressure'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='charge',
            field=models.DecimalField(decimal_places=2, help_text='Charge Amount', max_digits=10, null=True, verbose_name='Charges'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='cie_10_detail',
            field=models.TextField(blank=True, help_text='CIE-10 Diagnose Details', null=True, verbose_name='CIE-10 Detail'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='cie_10_group',
            field=models.OneToOneField(blank=True, help_text='CIE-10 group for the diagnose', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.Cie10Group', verbose_name='CIE-10 Group'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='datetime',
            field=models.DateTimeField(help_text='Date the consult will be done', null=True, verbose_name='Date & Time'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='diagnose',
            field=models.TextField(blank=True, help_text='Diagnose', null=True, verbose_name='Diagnose'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='digestive_system',
            field=models.TextField(blank=True, help_text='Digestive System Analysis', null=True, verbose_name='Digestive System'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='drugs',
            field=models.ManyToManyField(blank=True, help_text='Drugs recommended', to='appointments.Drug', verbose_name='Drugs'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='endocrine_system',
            field=models.TextField(blank=True, help_text='Endocrine System Analysis', null=True, verbose_name='Endocrine System'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='head_exploration',
            field=models.TextField(blank=True, help_text='Head Exploration Analysis', null=True, verbose_name='Head Exploration'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='indications',
            field=models.TextField(blank=True, help_text='Indications', null=True, verbose_name='Indications'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='lock',
            field=models.BooleanField(default=True, help_text='Consult lock status', null=True, verbose_name='Lock'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='lymphatic_system',
            field=models.TextField(blank=True, help_text='Lymphatic System Analysis', null=True, verbose_name='Lymphatic System'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='medical_status',
            field=models.BooleanField(blank=True, default=False, help_text='Handles the medical consult status', null=True, verbose_name='Medical Status'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='motive',
            field=models.TextField(help_text='The motive of your assistance to the consult', null=True, verbose_name='Motive'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='patient',
            field=models.ForeignKey(help_text='Patient assisting this consult', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consult', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='prescription',
            field=models.FileField(blank=True, help_text='Prescription', null=True, upload_to='appointments/prescriptions', verbose_name='Prescription'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='procedure',
            field=models.TextField(blank=True, help_text='Procedure', null=True, verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='renal_system',
            field=models.TextField(blank=True, help_text='Renal System Analysis', null=True, verbose_name='Renal System'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='respiratory_system',
            field=models.TextField(blank=True, help_text='Respiratory System Analysis', null=True, verbose_name='Respiratory System'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='size',
            field=models.FloatField(blank=True, help_text='Size', null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', help_text='Handles the consult status', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='suffering',
            field=models.TextField(help_text='What is the patient suffering?', null=True, verbose_name='Suffering'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Corporal Temperature', null=True, verbose_name='Temperature'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='thorax_exploration',
            field=models.TextField(blank=True, help_text='Thorax Exploration Analysis', null=True, verbose_name='Thorax Exploration'),
        ),
        migrations.AlterField(
            model_name='consult',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight', null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Drug created by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drug', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='medicalexam',
            name='consult',
            field=models.ForeignKey(blank=True, help_text='Medical Exams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='appointments.Consult', verbose_name='Medical Exams'),
        ),
    ]
