# Generated by Django 2.2.13 on 2021-01-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0049_auto_20210106_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cie10group',
            options={'verbose_name': 'CIE-10 Group', 'verbose_name_plural': 'CIE-10 Groups'},
        ),
        migrations.AlterModelOptions(
            name='consult',
            options={'verbose_name': 'Consult', 'verbose_name_plural': 'Consults'},
        ),
        migrations.AlterModelOptions(
            name='drug',
            options={'verbose_name': 'Drug', 'verbose_name_plural': 'Drugs'},
        ),
        migrations.AlterModelOptions(
            name='medicalexam',
            options={'verbose_name': 'Medical Exam', 'verbose_name_plural': 'Medical Exams'},
        ),
    ]
