# Generated by Django 2.2.13 on 2021-01-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0050_auto_20210108_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('BT', 'BT')], help_text='Test Type', max_length=100, null=True, verbose_name='Test Type')),
                ('name', models.CharField(help_text='Test Name', max_length=100, null=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Medical Test',
                'verbose_name_plural': 'Medical Tests',
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='prescribed_tests',
            field=models.ManyToManyField(blank=True, help_text='Prescribed Tests', to='appointments.MedicalTest', verbose_name='Prescribed Tests'),
        ),
    ]
