# Generated by Django 2.2.13 on 2021-01-27 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0051_auto_20210127_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaltest',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_test', to=settings.AUTH_USER_MODEL),
        ),
    ]
