# Generated by Django 2.2.13 on 2021-01-28 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0008_auto_20210108_0112'),
        ('appointments', '0052_medicaltest_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='recommended_lab',
            field=models.ForeignKey(blank=True, help_text='Recommended Laboratory', null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.Provider', verbose_name='Recommended Laboratory'),
        ),
    ]
