# Generated by Django 2.2.13 on 2021-01-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0053_consult_recommended_lab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consult',
            name='prescribed_tests',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='recommended_lab',
        ),
        migrations.DeleteModel(
            name='MedicalTest',
        ),
    ]
