# Generated by Django 2.2.13 on 2021-01-28 02:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0055_auto_20210128_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='consult',
            name='instructions',
            field=models.CharField(blank=True, help_text='Instructions', max_length=512, null=True, verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='medicaltestresult',
            name='type',
            field=models.CharField(choices=[('TEST', 'TEST')], help_text='Type of exams', max_length=100, null=True, verbose_name='type of exams'),
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('TEST', 'TEST')], help_text='Medical Test Type', max_length=100, null=True, verbose_name='Test Type')),
                ('name', models.CharField(help_text='Medical Test Name', max_length=150, null=True, verbose_name='Test Name')),
                ('created_by', models.ForeignKey(blank=True, help_text='Created By', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical_test', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Test',
                'verbose_name_plural': 'Medical Tests',
            },
        ),
        migrations.AddField(
            model_name='consult',
            name='testing',
            field=models.ManyToManyField(blank=True, help_text='Pending Testing', to='appointments.MedicalTest', verbose_name='Testing'),
        ),
    ]
