# Generated by Django 2.2.13 on 2021-02-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0056_auto_20210128_0216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicaltest',
            options={'ordering': ('name',), 'verbose_name': 'Medical Test', 'verbose_name_plural': 'Medical Tests'},
        ),
        migrations.AlterField(
            model_name='medicaltest',
            name='test_type',
            field=models.CharField(choices=[('AMN', 'Amniocentesis'), ('BA', 'Blood Analysis'), ('GFA', 'Gastric Fluid Analysis'), ('KFT', 'Kidney Function Test'), ('LFT', 'Liver Function Test'), ('LP', 'Lumbar Puncture'), ('MT', 'Malabsorption Test'), ('PS', 'PAP Smear'), ('PHT', 'Phenolsulfonphthalein Test'), ('PGT', 'Pregnancy Test'), ('PNT', 'Prenatal Test'), ('PBIO', 'Protein-Bound Iodine Test'), ('SYPT', 'Syphilis Test'), ('THOR', 'Thoracentesis'), ('TFT', 'Thyroid Function Test'), ('TXT', 'Toxicology Test'), ('UR', 'Urinalysis/Uroscopy'), ('DI', 'Diagnostic Imaging'), ('GT', 'Genetic Testing'), ('M', 'Measurement'), ('PAVE', 'Physical and Visual Examination')], help_text='Medical Test Type', max_length=100, null=True, verbose_name='Test Type'),
        ),
        migrations.AlterField(
            model_name='medicaltestresult',
            name='type',
            field=models.CharField(choices=[('AMN', 'Amniocentesis'), ('BA', 'Blood Analysis'), ('GFA', 'Gastric Fluid Analysis'), ('KFT', 'Kidney Function Test'), ('LFT', 'Liver Function Test'), ('LP', 'Lumbar Puncture'), ('MT', 'Malabsorption Test'), ('PS', 'PAP Smear'), ('PHT', 'Phenolsulfonphthalein Test'), ('PGT', 'Pregnancy Test'), ('PNT', 'Prenatal Test'), ('PBIO', 'Protein-Bound Iodine Test'), ('SYPT', 'Syphilis Test'), ('THOR', 'Thoracentesis'), ('TFT', 'Thyroid Function Test'), ('TXT', 'Toxicology Test'), ('UR', 'Urinalysis/Uroscopy'), ('DI', 'Diagnostic Imaging'), ('GT', 'Genetic Testing'), ('M', 'Measurement'), ('PAVE', 'Physical and Visual Examination')], help_text='Type of exams', max_length=100, null=True, verbose_name='type of exams'),
        ),
    ]
