# Generated by Django 2.2.13 on 2021-02-07 20:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0057_auto_20210201_2154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicaltest',
            unique_together={('test_type', 'name', 'created_by')},
        ),
    ]
