# Generated by Django 3.1.6 on 2021-04-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0058_auto_20210207_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaltestresult',
            name='consult',
            field=models.ForeignKey(blank=True, help_text='Medical Exams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='appointments.consult', verbose_name='Consult'),
        ),
    ]
