# Generated by Django 3.1.6 on 2021-05-07 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_auto_20210421_2355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0059_auto_20210421_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(help_text='Date the consult will be done', null=True, verbose_name='Date & Time')),
                ('motive', models.TextField(help_text='The motive of your assistance to the consult', null=True, verbose_name='Motive')),
                ('suffering', models.TextField(help_text='What is the patient suffering?', null=True, verbose_name='Suffering')),
                ('charge', models.DecimalField(decimal_places=2, help_text='Charge Amount', max_digits=10, null=True, verbose_name='Charges')),
                ('cie_10_detail', models.TextField(blank=True, help_text='CIE-10 Diagnose Details', null=True, verbose_name='CIE-10 Detail')),
                ('diagnose', models.TextField(blank=True, help_text='Diagnose', null=True, verbose_name='Diagnose')),
                ('procedure', models.TextField(blank=True, help_text='Procedure', null=True, verbose_name='Procedure')),
                ('analysis', models.TextField(blank=True, help_text='Analysis', null=True, verbose_name='Analysis')),
                ('notes', models.TextField(blank=True, help_text='Notes', null=True, verbose_name='Notes')),
                ('indications', models.TextField(blank=True, help_text='Indications', null=True, verbose_name='Indications')),
                ('actions', models.TextField(blank=True, help_text='Actions', null=True, verbose_name='Actions')),
                ('prescription', models.FileField(blank=True, help_text='Prescription', null=True, upload_to='appointments/prescriptions', verbose_name='Prescription')),
                ('instructions', models.CharField(blank=True, help_text='Instructions', max_length=512, null=True, verbose_name='Instructions')),
                ('medical_status', models.BooleanField(blank=True, default=False, help_text='Handles the medical consult status', null=True, verbose_name='Medical Status')),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='OPEN', help_text='Handles the consult status', max_length=10, null=True, verbose_name='Status')),
                ('lock', models.BooleanField(default=True, help_text='Consult lock status', null=True, verbose_name='Lock')),
                ('cie_10_group', models.OneToOneField(blank=True, help_text='CIE-10 group for the diagnose', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.cie10group', verbose_name='CIE-10 Group')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('drugs', models.ManyToManyField(blank=True, help_text='Drugs recommended', to='appointments.Drug', verbose_name='Drugs')),
                ('patient', models.ForeignKey(help_text='Patient assisting this consult', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consult', to='patients.patient', verbose_name='Patient')),
                ('testing', models.ManyToManyField(blank=True, help_text='Pending Testing', to='appointments.MedicalTest', verbose_name='Testing')),
            ],
            options={
                'verbose_name': 'Consult',
                'verbose_name_plural': 'Consults',
                'unique_together': {('created_by', 'datetime')},
            },
        ),
        migrations.CreateModel(
            name='AllergyAndImmunologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='DentalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='GeneralConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('blood_pressure', models.FloatField(blank=True, help_text='Blood Pressure', null=True, verbose_name='Blood Pressure')),
                ('temperature', models.FloatField(blank=True, help_text='Corporal Temperature', null=True, verbose_name='Temperature')),
                ('weight', models.FloatField(blank=True, help_text='Weight', null=True, verbose_name='Weight')),
                ('size', models.FloatField(blank=True, help_text='Size', null=True, verbose_name='Height')),
                ('digestive_system', models.TextField(blank=True, help_text='Digestive System Analysis', null=True, verbose_name='Digestive System')),
                ('endocrine_system', models.TextField(blank=True, help_text='Endocrine System Analysis', null=True, verbose_name='Endocrine System')),
                ('renal_system', models.TextField(blank=True, help_text='Renal System Analysis', null=True, verbose_name='Renal System')),
                ('lymphatic_system', models.TextField(blank=True, help_text='Lymphatic System Analysis', null=True, verbose_name='Lymphatic System')),
                ('respiratory_system', models.TextField(blank=True, help_text='Respiratory System Analysis', null=True, verbose_name='Respiratory System')),
                ('head_exploration', models.TextField(blank=True, help_text='Head Exploration Analysis', null=True, verbose_name='Head Exploration')),
                ('thorax_exploration', models.TextField(blank=True, help_text='Thorax Exploration Analysis', null=True, verbose_name='Thorax Exploration')),
            ],
            options={
                'verbose_name': 'General Consult',
                'verbose_name_plural': 'General Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='GynecologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='NeurologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='OphthalmologyConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='PsychiatryConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='SurgicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.CreateModel(
            name='UrologicalConsult',
            fields=[
                ('baseconsult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appointments.baseconsult')),
                ('general_notes', models.TextField(blank=True, help_text='Consult General Notes', null=True, verbose_name='General Notes')),
            ],
            options={
                'verbose_name': 'Allergy and Immunological Consult',
                'verbose_name_plural': 'Allergy and Immunological Consults',
            },
            bases=('appointments.baseconsult',),
        ),
        migrations.AlterField(
            model_name='medicaltestresult',
            name='consult',
            field=models.ForeignKey(blank=True, help_text='Medical Exams', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='appointments.baseconsult', verbose_name='Consult'),
        ),
        migrations.DeleteModel(
            name='Consult',
        ),
    ]
