# Generated by Django 3.1.6 on 2021-05-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0060_auto_20210507_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dentalconsult',
            options={'verbose_name': 'Dental Consult', 'verbose_name_plural': 'Dental Consults'},
        ),
        migrations.AlterModelOptions(
            name='gynecologicalconsult',
            options={'verbose_name': 'Gynecological Consult', 'verbose_name_plural': 'Gynecological Consults'},
        ),
        migrations.AlterModelOptions(
            name='neurologicalconsult',
            options={'verbose_name': 'Neurological Consult', 'verbose_name_plural': 'Neurological Consults'},
        ),
        migrations.AlterModelOptions(
            name='ophthalmologyconsult',
            options={'verbose_name': 'Ophthalmology Consult', 'verbose_name_plural': 'Ophthalmology Consults'},
        ),
        migrations.AlterModelOptions(
            name='psychiatryconsult',
            options={'verbose_name': 'Psychiatry Consult', 'verbose_name_plural': 'Psychiatry Consults'},
        ),
        migrations.AlterModelOptions(
            name='surgicalconsult',
            options={'verbose_name': 'Surgical Consult', 'verbose_name_plural': 'Surgical Consults'},
        ),
        migrations.AlterModelOptions(
            name='urologicalconsult',
            options={'verbose_name': 'Urological Consult', 'verbose_name_plural': 'Urological Consults'},
        ),
        migrations.AlterField(
            model_name='medicaltestresult',
            name='type',
            field=models.CharField(choices=[('AP', 'Antipyretics'), ('AG', 'Analgesics'), ('AM', 'Antimalarial'), ('AB', 'Antibiotics'), ('AS', 'Antiseptics'), ('MS', 'Mood Stabilizers'), ('HR', 'Hormone Replacement'), ('OC', 'Oral Contraceptives'), ('S', 'Stimulants'), ('T', 'Tranquilizers'), ('ST', 'Statins')], help_text='Type of exams', max_length=100, null=True, verbose_name='type of exams'),
        ),
    ]
