# Generated by Django 3.1.6 on 2021-05-11 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_auto_20210421_2355'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0061_auto_20210510_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Vaccine name', max_length=100, null=True, verbose_name='Name')),
                ('scientific_name', models.CharField(blank=True, help_text="Vaccine's scientific name", max_length=100, null=True, verbose_name='Scientific Name')),
                ('purpose', models.TextField(help_text="Vaccine's purpose", null=True, verbose_name='Purpose')),
                ('laboratory', models.CharField(blank=True, help_text='Laboratory', max_length=100, null=True, verbose_name='Laboratory')),
                ('comments', models.TextField(blank=True, help_text='Comments about the vaccine', null=True, verbose_name='Comments')),
                ('created_by', models.ForeignKey(blank=True, help_text='Created_by', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VaccineApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(help_text='Surgery date and time', null=True, verbose_name='Datetime')),
                ('comments', models.TextField(blank=True, help_text='Surgery comments or important notes', null=True, verbose_name='Comments')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient receiving the surgery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccine', to='patients.patient')),
                ('vaccine_applied', models.ForeignKey(help_text='Vaccine Applied', null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.vaccine', verbose_name='Vaccine')),
            ],
            options={
                'verbose_name': 'Vaccine applied',
                'verbose_name_plural': 'Vaccines applied',
                'ordering': ('datetime',),
            },
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(help_text='Surgery date and time', null=True, verbose_name='Datetime')),
                ('about', models.TextField(blank=True, help_text='Information about the surgery', null=True, verbose_name='About')),
                ('comments', models.TextField(blank=True, help_text='Surgery comments or important notes', null=True, verbose_name='Comments')),
                ('status', models.CharField(blank=True, choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], help_text='Surgery status', max_length=10, null=True, verbose_name='Status')),
                ('medical_status', models.BooleanField(blank=True, default=False, help_text='Medical Surgery Status', null=True, verbose_name='Medical Status')),
                ('patient', models.ForeignKey(blank=True, help_text='Patient receiving the surgery', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgery', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Surgery',
                'verbose_name_plural': 'Surgeries',
                'ordering': ('datetime',),
            },
        ),
    ]
