# Generated by Django 3.1.6 on 2021-05-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0062_surgery_vaccine_vaccineapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgery',
            name='surgery_type',
            field=models.CharField(help_text='Surgery Type', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
