# Generated by Django 3.1.6 on 2021-05-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0063_surgery_surgery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surgery',
            name='datetime',
            field=models.DateTimeField(help_text='Surgery date and time', null=True, verbose_name='Datetime'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.CharField(choices=[('BAS', 'Bariatric Surgery'), ('BRS', 'Breast Surgery'), ('CRS', 'Colon and Rectal Surgery'), ('ES', 'Endocrine Surgery'), ('GS', 'General Surgery'), ('GYS', 'Gynecological Surgery'), ('HS', 'Hand Surgery'), ('HRS', 'Hernia Surgery'), ('NEUS', 'Neurological Surgery'), ('ORTS', 'Orthopedic Surgery'), ('OPHS', 'Ophthalmological Surgery'), ('OUTS', 'Outpatient Surgery'), ('PS', 'Pediatric Surgery'), ('PRS', 'Plastic and Reconstructive Surgery'), ('RS', 'Robotic Surgery'), ('THS', 'Thoracic Surgery'), ('TRS', 'Trauma Surgery'), ('US', 'Urological Surgery'), ('VS', 'Vascular Surgery'), ('MIS', 'Minimally Invasive Surgery')], help_text='Surgery Type', max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='vaccineapplication',
            name='datetime',
            field=models.DateTimeField(help_text='Surgery date and time', null=True, verbose_name='Datetime'),
        ),
    ]
