# Generated by Django 3.1.6 on 2021-07-03 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0065_auto_20210521_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseconsult',
            options={'ordering': ('datetime',), 'verbose_name': 'Consult', 'verbose_name_plural': 'Consults'},
        ),
    ]
