# Generated by Django 3.1.6 on 2021-07-12 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0066_auto_20210703_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalconsult',
            name='blood_pressure',
            field=models.CharField(blank=True, help_text='Blood Pressure', max_length=10, null=True, verbose_name='Blood Pressure'),
        ),
    ]
