# Generated by Django 3.1.6 on 2021-07-27 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0068_auto_20210717_2356'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccineapplication',
            options={'ordering': ('-datetime',), 'verbose_name': 'Vaccine applied', 'verbose_name_plural': 'Vaccines applied'},
        ),
    ]
