# Generated by Django 2.2.13 on 2020-07-03 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy_type', models.CharField(help_text='Allergy Type', max_length=100, verbose_name='allergy')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceCarrier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Insurance Carrier', max_length=100, verbose_name='company')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(blank=True, help_text='Provide you ID Card Number', max_length=20, null=True, verbose_name='ID number')),
                ('first_names', models.CharField(help_text="Patient's Name", max_length=50, verbose_name='patients name')),
                ('last_names', models.CharField(help_text="Patient's Last Name", max_length=50, verbose_name='patients last name')),
                ('birthday', models.DateTimeField(help_text='Patients date of birth', verbose_name='patients birthday')),
                ('age', models.IntegerField(verbose_name='patients age')),
                ('civil_status', models.CharField(choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('WIDOWED', 'Widowed'), ('DIVORCED', 'Divorced'), ('SEPARATED', 'Separated')], max_length=12)),
                ('procedence', models.CharField(choices=[('HONDURAS', 'Honduras')], max_length=50)),
                ('residence', models.CharField(choices=[('HONDURAS', 'Honduras')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_insurance', models.CharField(choices=[('MEDICAL', 'Medical')], help_text='Type of insurnace', max_length=50, null=True, verbose_name='insurance type')),
                ('expiration_date', models.DateField(help_text='insurance date expiration', verbose_name='insurance date expiration')),
                ('insurance_carrier', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.InsuranceCarrier', verbose_name='insurance carrier')),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patient', verbose_name='insurance owner')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedent', models.CharField(blank=True, help_text='Antecedent Type', max_length=150, null=True, verbose_name='antecedent')),
                ('info', models.TextField(blank=True, help_text='About this antecedent', null=True, verbose_name='antecedent info')),
                ('patient', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='Patient')),
            ],
        ),
        migrations.CreateModel(
            name='AllergiesInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(help_text='Tell us about what you suffer', verbose_name='about allergy')),
                ('allergy_type', models.OneToOneField(blank=True, help_text='Allergy type of the patient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy', to='patients.Allergies', verbose_name='allergy type')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='Patient')),
            ],
        ),
    ]
