# Generated by Django 2.2.13 on 2020-07-04 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='procedence',
            new_name='origin',
        ),
    ]
