# Generated by Django 2.2.13 on 2020-07-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200704_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=20, null=True, verbose_name='phone number'),
        ),
    ]
