# Generated by Django 2.2.13 on 2020-07-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200704_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinformation',
            name='type_of_insurance',
            field=models.CharField(blank=True, choices=[('MEDICAL', 'Medical')], help_text='Type of insurance', max_length=50, null=True, verbose_name='insurance type'),
        ),
    ]
