# Generated by Django 2.2.13 on 2020-07-04 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200704_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergiesinformation',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Patient', verbose_name='Patient'),
        ),
    ]
