# Generated by Django 2.2.13 on 2020-07-05 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200704_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergiesinformation',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='antecedents',
            name='patient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.Patient', verbose_name='insurance owner'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='civil_status',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('W', 'Widowed'), ('D', 'Divorced'), ('SP', 'Separated')], max_length=12),
        ),
        migrations.AlterField(
            model_name='patient',
            name='origin',
            field=models.CharField(choices=[('HND', 'Honduras')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence',
            field=models.CharField(choices=[('HND', 'Honduras')], max_length=50),
        ),
    ]
