# Generated by Django 2.2.13 on 2020-07-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20200707_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.DurationField(null=True, verbose_name='patients age'),
        ),
    ]
