# Generated by Django 2.2.13 on 2020-07-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20200707_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
