# Generated by Django 2.2.13 on 2020-07-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20200708_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancecarrier',
            name='country',
            field=models.CharField(choices=[('HND', 'Honduras'), ('NIC', 'Nicaragua')], default=None, help_text='Insurance Carrier origin', max_length=100, null=True, verbose_name='country'),
        ),
    ]
