# Generated by Django 2.2.13 on 2020-07-08 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20200708_0059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insurancecarrier',
            unique_together={('company', 'country')},
        ),
    ]
