# Generated by Django 2.2.13 on 2020-07-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0018_auto_20200708_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergies',
            name='created_by',
            field=models.CharField(help_text='User by who the allergy was created.', max_length=100, null=True, verbose_name='created by user'),
        ),
        migrations.AlterUniqueTogether(
            name='allergies',
            unique_together={('allergy_type', 'created_by')},
        ),
    ]
