# Generated by Django 2.2.13 on 2020-07-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_auto_20200709_1643'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allergies',
            unique_together=set(),
        ),
    ]
