# Generated by Django 2.2.13 on 2020-07-09 20:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0022_auto_20200709_2022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='allergies',
            unique_together={('allergy_type', 'created_by')},
        ),
    ]
