# Generated by Django 2.2.13 on 2020-07-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_patient_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(help_text='Patients date of birth', verbose_name='patients birthday'),
        ),
    ]
