# Generated by Django 2.2.13 on 2020-09-09 18:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0027_auto_20200712_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecarrier',
            name='created_by',
            field=models.ForeignKey(help_text='Who created this insurance carrier', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Author', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
    ]
