# Generated by Django 2.2.13 on 2020-09-09 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0028_insurancecarrier_created_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insurancecarrier',
            unique_together=set(),
        ),
    ]
