# Generated by Django 2.2.13 on 2020-09-09 21:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0029_auto_20200909_1802'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='insurancecarrier',
            unique_together={('company', 'created_by')},
        ),
    ]
