# Generated by Django 2.2.13 on 2020-09-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_auto_20200909_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text="Patient's Email Address", max_length=254, null=True, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculine'), ('F', 'Femenine'), ('O', 'Other')], help_text="Patient's Gender", max_length=15, null=True, verbose_name='gender'),
        ),
    ]
