# Generated by Django 2.2.13 on 2020-09-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_auto_20200916_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
