# Generated by Django 2.2.13 on 2020-09-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_auto_20200917_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.EmailField(help_text='Email', max_length=254, null=True, verbose_name="Patient's Email"),
        ),
    ]
