# Generated by Django 2.2.13 on 2020-09-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Email', max_length=254, null=True, verbose_name="Patient's Email"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(help_text='Gender', max_length=20, null=True, verbose_name="Patient's Gender"),
        ),
    ]
