# Generated by Django 2.2.13 on 2020-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0035_auto_20200917_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(help_text='Patients date of birth', verbose_name="Patient's Birthday"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_names',
            field=models.CharField(help_text="Patient's Name", max_length=50, verbose_name="Patient's Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_names',
            field=models.CharField(help_text="Patient's Last Name", max_length=50, verbose_name="Patient's Last Name"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone Number', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
