# Generated by Django 2.2.13 on 2020-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_auto_20201007_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_number',
            field=models.CharField(blank=True, help_text='Provide you ID Card Number', max_length=20, null=True, verbose_name='ID Number'),
        ),
    ]
