# Generated by Django 2.2.13 on 2020-10-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0037_auto_20201007_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergiesinformation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergies', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='antecedents',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedents', to='patients.Patient', verbose_name='Patient'),
        ),
    ]
