# Generated by Django 2.2.13 on 2020-10-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0039_auto_20201010_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceinformation',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.Patient', verbose_name='insurance owner'),
        ),
    ]
