# Generated by Django 2.2.13 on 2020-12-13 15:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0041_auto_20201023_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Allergies',
            new_name='Allergy',
        ),
        migrations.RenameModel(
            old_name='AllergiesInformation',
            new_name='AllergyInformation',
        ),
        migrations.RenameModel(
            old_name='Antecedents',
            new_name='Antecedent',
        ),
    ]
