# Generated by Django 2.2.13 on 2021-01-06 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_auto_20201213_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='allergy_type',
            field=models.CharField(help_text='Allergy Type', max_length=100, verbose_name='Allergy'),
        ),
        migrations.AlterField(
            model_name='allergyinformation',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About Allergy'),
        ),
        migrations.AlterField(
            model_name='allergyinformation',
            name='allergy_type',
            field=models.ForeignKey(blank=True, help_text='Allergy type of the patient', null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.Allergy', verbose_name='Allergy Type'),
        ),
        migrations.AlterField(
            model_name='allergyinformation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_information', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='antecedent',
            field=models.CharField(blank=True, help_text='Antecedent Type', max_length=150, null=True, verbose_name='Antecedent'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='info',
            field=models.TextField(blank=True, help_text='About this antecedent', null=True, verbose_name='Antecedent Information'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedent', to='patients.Patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='insurancecarrier',
            name='company',
            field=models.CharField(help_text='Insurance Carrier', max_length=100, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='insurancecarrier',
            name='country',
            field=models.CharField(choices=[('HND', 'Honduras'), ('NIC', 'Nicaragua')], default=None, help_text='Insurance Carrier origin', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='insurancecarrier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_carrier', to=settings.AUTH_USER_MODEL, verbose_name='created_by'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='expiration_date',
            field=models.DateField(help_text="Insurance's Expiration Date", verbose_name='Expiration Date'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='insurance_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.InsuranceCarrier', verbose_name='Insurance Carrier'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='patient',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='patients.Patient', verbose_name='Insurance Owner'),
        ),
        migrations.AlterField(
            model_name='insuranceinformation',
            name='type_of_insurance',
            field=models.CharField(blank=True, choices=[('MEDICAL', 'Medical')], help_text='Type of insurance', max_length=50, null=True, verbose_name='Insurance Type'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
