# Generated by Django 2.2.13 on 2021-01-08 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0043_auto_20210106_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name': 'Allergy', 'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='allergyinformation',
            options={'verbose_name': 'Allergy Information', 'verbose_name_plural': "Patient's Allergic Information"},
        ),
        migrations.AlterModelOptions(
            name='antecedent',
            options={'verbose_name': 'Antecedent', 'verbose_name_plural': 'Antecedents'},
        ),
        migrations.AlterModelOptions(
            name='insurancecarrier',
            options={'verbose_name': 'Insurance Carrier', 'verbose_name_plural': 'Insurance Carriers'},
        ),
        migrations.AlterModelOptions(
            name='insuranceinformation',
            options={'verbose_name': 'Insurance Information', 'verbose_name_plural': "Patient's Insurance Data"},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
    ]
