# Generated by Django 2.2.13 on 2021-01-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0044_auto_20210108_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='origin',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('BZ', 'Belize'), ('CA', 'Canada'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'Mexico'), ('NI', 'Nicaragua'), ('PA', 'Panama'), ('SV', 'El Salvador'), ('US', 'United States')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='residence',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BR', 'Brazil'), ('BZ', 'Belize'), ('CA', 'Canada'), ('CL', 'Chile'), ('CO', 'Colombia'), ('CR', 'Costa Rica'), ('GT', 'Guatemala'), ('HN', 'Honduras'), ('MX', 'Mexico'), ('NI', 'Nicaragua'), ('PA', 'Panama'), ('SV', 'El Salvador'), ('US', 'United States')], max_length=50),
        ),
    ]
