# Generated by Django 3.1.6 on 2021-04-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0045_auto_20210127_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergyinformation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_info', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedent_info', to='patients.patient', verbose_name='Patient'),
        ),
    ]
