# Generated by Django 3.1.6 on 2021-06-17 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0046_auto_20210421_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_created',
            field=models.DateField(blank=True, help_text='Date Created', null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='allergyinformation',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allergy_information', to='patients.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='antecedent',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antecedent_information', to='patients.patient', verbose_name='Patient'),
        ),
    ]
